# Generated by Django 5.0 on 2023-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_data',
            name='created_by',
            field=models.CharField(blank=True, choices=[('Amit', 'Amit'), ('Aditya', 'Aditya')], max_length=10, null=True),
        ),
    ]
