# Generated by Django 5.0 on 2023-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_membership_data_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_data',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Half-year', 'Half-year'), ('Yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
