# Generated by Django 5.0 on 2023-12-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_membership_data_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(help_text='Specify the payment amount.', max_length=10)),
                ('paid_by', models.CharField(choices=[('Cash', 'Cash'), ('Upi', 'Upi')], default='------', help_text='Choose the mode of payment.', max_length=5)),
                ('created_by', models.CharField(choices=[('Amit', 'Amit'), ('Aditya', 'Aditya')], default='------', help_text='Select the trainer.', max_length=10)),
                ('plan_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-year', 'Half-year'), ('Yearly', 'Yearly')], default='------', help_text='Select the plan type.', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Membership_data',
        ),
    ]
