# Generated by Django 5.0 on 2023-12-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_dailyentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='create_time',
            new_name='entry_time',
        ),
    ]
