# Generated by Django 5.0 on 2023-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_dailyentry_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
