# Generated by Django 5.0 on 2023-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_membershipdata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdata',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
